version: '3'
services:
  docker-bike-shop:
    restart: always
    container_name: docker-bike-shop
    image: bike-shop
    environment:
      MYSQL_DATABASE: velikone
      MYSQL_ROOT_USER: hypo
      MYSQL_ROOT_PASSWORD: hypo#123
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

    ports:
      - "6033:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=hypo --password=hypo#123--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  book-manager-app:
    restart: on-failure
    build: ./
    expose:
      - "8080"
    ports:
      - 8080:8080
    environment:
      WAIT_HOSTS: bike-shop:3306
    depends_on:
      - docker-bike-shop